#+TITLE: Spider Diagrams
#+AUTHOR:
#+DATE:
#+OPTIONS: toc:nil
* What Was the Main Influence Behind the 1559 Religious Settlement?
  - Domestic v foreign affairs: in fact, these seem to point in the same direction, towards compromise
  - Power: Elizabeth v PC v Parliament v Clergy. Where did these overlap? Who was most powerful?
  - Elizabeth: What is the significance of her beliefs? Does it matter for these purposes that she is a woman?
  - Most significant factor: What is the most significant factor? Presumably domestic affairs?
  - Change over time: Did foreign affairs become less important? As the stability of the regime increase, is there any evidence that there was less religious compromise? If not, does that show that Elizabeth didn't hold strongly Protestant views?
* How Serious was the Catholic Threat?
  - Threat to the RS itself: This is a threat without damaging wider stability. Did this change over time? Once the RS was passed, was there a danger that it would be undone? Was there a danger that the Marian clergy would simply not follow it? What in particular did they find offensive about it?
  - Threat to Elizabeth as monarch/personally: Did Catholics enjoy enough popular support to seriously threaten Elizabeth? How do we know? Did that change overtime?
  - Factors: Was the Catholic threat handled well by Elizabeth and her supporters, or was it actually not all that significant?
  - Domestic v foreign: what was the greater threat? English mission v simple invasion. How successful were the plots against Elizabeth? Were they over-blown by a sense of paranoia?
* Impact of Marriage and Succession on Domestic Affairs
  - Change over time: How and why did this become less of a problem over the course of her reign?
  - Link to other matters: That Elizabeth is a female ruler (the link is obvious); religious issues (supporters of certain marriages presumably see this as an opportunity to increase their religious faction's strength; MQS is a threat that could encourage marriage); who has power - Parliament, the Queen or the PC, and how do these interact? Does popular opinion have a role in this (and is that particularly deposed to be anti-Catholic because of Catholicism seeming foreign)?
  - In what ways did marriage and succession have a significant impact? (In PC, in eventually prompting action against MQS, perhaps in foreign affairs).  In what ways was its impact limited? (Perhaps in relations with Parliament, perhaps in terms of the plots themselves, perhaps in turning public opinion against Elizabeth?)
* How Serious Was The Puritan Threat?
  - Defining: What is puritanism?
  - Extent: When was it a threat? Where and how did this threat manifest itself?
  - Link to other matters: Did the threat predominantly come from Parliament, from the Church, or from the grassroots? How are these linked? How do we connect this to the other threats which we know emanated from the same bodies?
  - Nature and severity: What did Puritans want? Were they a unified group?
  - Cause: Why was puritanism a threat/not a threat?
